/*
 * Templete for Clients
 */
package proyectotienda;

import conexionmysql.DatosConexion;
import static conexionmysql.DatosConexion.CONEXION;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Héctor Menduíña Hermelo
 */
public final class Cliente extends javax.swing.JFrame implements DatosConexion {
    public String codigoCli ;
    public String nombreCli ;
    public String apellidosCli ;
    public String dniCli;
    public String direccionCli ;
    public String emailCli;
    public String telefonoCli ;
    public String sexoCli ;
    //ConectarMySQL conexion = new ConectarMySQL("localhost","proyectotienda","root","hector");
    private DefaultTableModel DfmodeloClientes = new DefaultTableModel();
    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
         //vaciamos la tabla de filas
       DfmodeloClientes.setColumnCount(0);
       DfmodeloClientes.setRowCount(0);
       //Añadimos las columnas al modelo de la tabla para los clientes
       DfmodeloClientes.addColumn("COD");
       DfmodeloClientes.addColumn("NOMBRE");
       DfmodeloClientes.addColumn("APELLIDOS");
       DfmodeloClientes.addColumn("DNI");
       DfmodeloClientes.addColumn("DIRECCION");
       DfmodeloClientes.addColumn("E-mail");
       DfmodeloClientes.addColumn("TELEFONO");
       DfmodeloClientes.addColumn("SEXO");
       
       resultadoListaClientes();
       TxtClienteCodigo.setText(calculaIDCliente());
       TxtClienteCodigo.setEnabled(false);
       
       ComboSexoCliente.addItem("Hombre");
       ComboSexoCliente.addItem("Mujer");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatosCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtClienteCodigo = new javax.swing.JTextField();
        TxtClienteNombre = new javax.swing.JTextField();
        TxtClienteTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtClienteEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtClienteDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtClienteApellidos = new javax.swing.JTextField();
        TxtClienteDNI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ComboSexoCliente = new javax.swing.JComboBox();
        PanelListaClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListaClientes = new javax.swing.JTable();
        PanelBotonesProducto = new javax.swing.JPanel();
        BtnAgregarProducto = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CODIGO:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("TELEFONO:");

        TxtClienteCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClienteCodigoActionPerformed(evt);
            }
        });

        TxtClienteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClienteNombreActionPerformed(evt);
            }
        });

        TxtClienteTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClienteTelefonoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("DNI:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("E-MAIL:");

        TxtClienteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClienteEmailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("DIRECCIÓN:");

        TxtClienteDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClienteDireccionActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("APELLIDOS");

        TxtClienteApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClienteApellidosActionPerformed(evt);
            }
        });

        TxtClienteDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClienteDNIActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("SEXO:");

        ComboSexoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
        }));

        javax.swing.GroupLayout PanelDatosClienteLayout = new javax.swing.GroupLayout(PanelDatosCliente);
        PanelDatosCliente.setLayout(PanelDatosClienteLayout);
        PanelDatosClienteLayout.setHorizontalGroup(
            PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtClienteDNI))
                    .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtClienteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboSexoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtClienteDireccion))
                    .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                        .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtClienteApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        PanelDatosClienteLayout.setVerticalGroup(
            PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtClienteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TxtClienteApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)
                        .addComponent(ComboSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                        .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(TxtClienteDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(TxtClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        PanelListaClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        TablaListaClientes.setModel(DfmodeloClientes);
        jScrollPane1.setViewportView(TablaListaClientes);

        BtnAgregarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnAgregarProducto.setText("Agregar");
        BtnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarProductoActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesProductoLayout = new javax.swing.GroupLayout(PanelBotonesProducto);
        PanelBotonesProducto.setLayout(PanelBotonesProductoLayout);
        PanelBotonesProductoLayout.setHorizontalGroup(
            PanelBotonesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelBotonesProductoLayout.setVerticalGroup(
            PanelBotonesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBotonesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregarProducto)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelListaClientesLayout = new javax.swing.GroupLayout(PanelListaClientes);
        PanelListaClientes.setLayout(PanelListaClientesLayout);
        PanelListaClientesLayout.setHorizontalGroup(
            PanelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(PanelBotonesProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelListaClientesLayout.setVerticalGroup(
            PanelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelBotonesProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtClienteCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClienteCodigoActionPerformed

    }//GEN-LAST:event_TxtClienteCodigoActionPerformed

    private void TxtClienteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClienteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtClienteNombreActionPerformed

    private void TxtClienteTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClienteTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtClienteTelefonoActionPerformed

    private void TxtClienteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClienteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtClienteEmailActionPerformed

    private void TxtClienteDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClienteDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtClienteDireccionActionPerformed

    private void TxtClienteApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClienteApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtClienteApellidosActionPerformed

    private void TxtClienteDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClienteDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtClienteDNIActionPerformed

    private void BtnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarProductoActionPerformed
        agregarCliente();
        resultadoListaClientes();
    }//GEN-LAST:event_BtnAgregarProductoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarProducto;
    private javax.swing.JComboBox ComboSexoCliente;
    private javax.swing.JPanel PanelBotonesProducto;
    private javax.swing.JPanel PanelDatosCliente;
    private javax.swing.JPanel PanelListaClientes;
    private javax.swing.JTable TablaListaClientes;
    private javax.swing.JTextField TxtClienteApellidos;
    private javax.swing.JTextField TxtClienteCodigo;
    private javax.swing.JTextField TxtClienteDNI;
    private javax.swing.JTextField TxtClienteDireccion;
    private javax.swing.JTextField TxtClienteEmail;
    private javax.swing.JTextField TxtClienteNombre;
    private javax.swing.JTextField TxtClienteTelefono;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void agregarCliente() throws NumberFormatException {
        setCodigoCli(this.getTxtClienteCodigo().getText());
        setNombreCli(getTxtClienteNombre().getText());
        setApellidosCli(getTxtClienteApellidos().getText());
        setDniCli(getTxtClienteDNI().getText());
        setDireccionCli(getTxtClienteDireccion().getText());
        setEmailCli(getTxtClienteEmail().getText());
        setTelefonoCli(getTxtClienteTelefono().getText());
        setSexoCli((String) getComboSexoCliente().getSelectedItem());
        

       CONEXION.ejecutar("insert into clientes values('"+getCodigoCli()+"','"+getNombreCli()+"','"+getApellidosCli()+"','"+getDniCli()+"'"
                 + ",'"+getDireccionCli()+"','"+getEmailCli()+"',"+getTelefonoCli()+",'"+getSexoCli()+"');");
        
        getTxtClienteApellidos().setText("");
        getTxtClienteCodigo().setText("");
        getTxtClienteDNI().setText("");
        getTxtClienteDireccion().setText("");
        getTxtClienteEmail().setText("");
        getTxtClienteNombre().setText("");
        getTxtClienteTelefono().setText("");
        resultadoListaClientes();
    }

    public void resultadoListaClientes() {
        try {
            getDfmodeloClientes().setRowCount(0);
           ResultSet filas = CONEXION.Consultar("select * from clientes order by codigoCli;");
                     while(filas.next()){
                       getDfmodeloClientes().addRow(new Object[] {filas.getString(1),filas.getString(2),filas.getString(3),filas.getString(4),
                       filas.getString(5),filas.getString(6),filas.getInt(7),filas.getString(8)});
                       //Creamos la tabla 
                       JTable DatosCliente = new JTable(getDfmodeloClientes());
                       //Añadimos el modelo de la tabla a la tabla
                       getTablaListaClientes().add(DatosCliente);
                       }
               getTablaListaClientes().setVisible(true);
       } catch (SQLException ex) {
           Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
    
    private String calculaIDCliente(){
        ResultSet datos = CONEXION.Consultar("select count(*) idClientes from clientes");
        String idRetornado="";
        try {
            while(datos.next()){
                if(datos.getInt("idClientes")==0){
                    idRetornado =  "C1";
                }else{
                    ResultSet ultimo_ID = CONEXION.Consultar("select codigoCli from clientes order by codigoCli desc limit 1;");
                    while(ultimo_ID.next()){
                        idRetornado = ultimo_ID.getString("codigoCli");
                    }
                    idRetornado = idRetornado.substring(1, idRetornado.length());
                    int numero = Integer.valueOf(idRetornado)+1;
                    idRetornado = "C"+numero;
                }
            } 
        } catch (SQLException ex) {}

        return idRetornado;
    }

    /**
     * @return the PanelListaClientes
     */
    public javax.swing.JPanel getPanelListaClientes() {
        return PanelListaClientes;
    }

    /**
     * @param PanelListaClientes the PanelListaClientes to set
     */
    public void setPanelListaClientes(javax.swing.JPanel PanelListaClientes) {
        this.PanelListaClientes = PanelListaClientes;
    }

    /**
     * @return the TablaListaClientes
     */
    public javax.swing.JTable getTablaListaClientes() {
        return TablaListaClientes;
    }

    /**
     * @param TablaListaClientes the TablaListaClientes to set
     */
    public void setTablaListaClientes(javax.swing.JTable TablaListaClientes) {
        this.TablaListaClientes = TablaListaClientes;
    }

    /**
     * @return the codigoCli
     */
    public String getCodigoCli() {
        return codigoCli;
    }

    /**
     * @param codigoCli the codigoCli to set
     */
    public void setCodigoCli(String codigoCli) {
        this.codigoCli = codigoCli;
    }

    /**
     * @return the nombreCli
     */
    public String getNombreCli() {
        return nombreCli;
    }

    /**
     * @param nombreCli the nombreCli to set
     */
    public void setNombreCli(String nombreCli) {
        this.nombreCli = nombreCli;
    }

    /**
     * @return the apellidosCli
     */
    public String getApellidosCli() {
        return apellidosCli;
    }

    /**
     * @param apellidosCli the apellidosCli to set
     */
    public void setApellidosCli(String apellidosCli) {
        this.apellidosCli = apellidosCli;
    }

    /**
     * @return the dniCli
     */
    public String getDniCli() {
        return dniCli;
    }

    /**
     * @param dniCli the dniCli to set
     */
    public void setDniCli(String dniCli) {
        this.dniCli = dniCli;
    }

    /**
     * @return the direccionCli
     */
    public String getDireccionCli() {
        return direccionCli;
    }

    /**
     * @param direccionCli the direccionCli to set
     */
    public void setDireccionCli(String direccionCli) {
        this.direccionCli = direccionCli;
    }

    /**
     * @return the emailCli
     */
    public String getEmailCli() {
        return emailCli;
    }

    /**
     * @param emailCli the emailCli to set
     */
    public void setEmailCli(String emailCli) {
        this.emailCli = emailCli;
    }

    /**
     * @return the telefonoCli
     */
    public String getTelefonoCli() {
        return telefonoCli;
    }

    /**
     * @param telefonoCli the telefonoCli to set
     */
    public void setTelefonoCli(String telefonoCli) {
        this.telefonoCli = telefonoCli;
    }

    /**
     * @return the sexoCli
     */
    public String getSexoCli() {
        return sexoCli;
    }

    /**
     * @param sexoCli the sexoCli to set
     */
    public void setSexoCli(String sexoCli) {
        this.sexoCli = sexoCli;
    }

    /**
     * @return the DfmodeloClientes
     */
    public DefaultTableModel getDfmodeloClientes() {
        return DfmodeloClientes;
    }

    /**
     * @param DfmodeloClientes the DfmodeloClientes to set
     */
    public void setDfmodeloClientes(DefaultTableModel DfmodeloClientes) {
        this.DfmodeloClientes = DfmodeloClientes;
    }

    /**
     * @return the BtnAgregarProducto
     */
    public javax.swing.JButton getBtnAgregarProducto() {
        return BtnAgregarProducto;
    }

    /**
     * @param BtnAgregarProducto the BtnAgregarProducto to set
     */
    public void setBtnAgregarProducto(javax.swing.JButton BtnAgregarProducto) {
        this.BtnAgregarProducto = BtnAgregarProducto;
    }

    /**
     * @return the ComboSexoCliente
     */
    public javax.swing.JComboBox getComboSexoCliente() {
        return ComboSexoCliente;
    }

    /**
     * @param ComboSexoCliente the ComboSexoCliente to set
     */
    public void setComboSexoCliente(javax.swing.JComboBox ComboSexoCliente) {
        this.ComboSexoCliente = ComboSexoCliente;
    }

    /**
     * @return the PanelBotonesProducto
     */
    public javax.swing.JPanel getPanelBotonesProducto() {
        return PanelBotonesProducto;
    }

    /**
     * @param PanelBotonesProducto the PanelBotonesProducto to set
     */
    public void setPanelBotonesProducto(javax.swing.JPanel PanelBotonesProducto) {
        this.PanelBotonesProducto = PanelBotonesProducto;
    }

    /**
     * @return the PanelDatosCliente
     */
    public javax.swing.JPanel getPanelDatosCliente() {
        return PanelDatosCliente;
    }

    /**
     * @param PanelDatosCliente the PanelDatosCliente to set
     */
    public void setPanelDatosCliente(javax.swing.JPanel PanelDatosCliente) {
        this.PanelDatosCliente = PanelDatosCliente;
    }

    /**
     * @return the TxtClienteApellidos
     */
    public javax.swing.JTextField getTxtClienteApellidos() {
        return TxtClienteApellidos;
    }

    /**
     * @param TxtClienteApellidos the TxtClienteApellidos to set
     */
    public void setTxtClienteApellidos(javax.swing.JTextField TxtClienteApellidos) {
        this.TxtClienteApellidos = TxtClienteApellidos;
    }

    /**
     * @return the TxtClienteCodigo
     */
    public javax.swing.JTextField getTxtClienteCodigo() {
        return TxtClienteCodigo;
    }

    /**
     * @param TxtClienteCodigo the TxtClienteCodigo to set
     */
    public void setTxtClienteCodigo(javax.swing.JTextField TxtClienteCodigo) {
        this.TxtClienteCodigo = TxtClienteCodigo;
    }

    /**
     * @return the TxtClienteDNI
     */
    public javax.swing.JTextField getTxtClienteDNI() {
        return TxtClienteDNI;
    }

    /**
     * @param TxtClienteDNI the TxtClienteDNI to set
     */
    public void setTxtClienteDNI(javax.swing.JTextField TxtClienteDNI) {
        this.TxtClienteDNI = TxtClienteDNI;
    }

    /**
     * @return the TxtClienteDireccion
     */
    public javax.swing.JTextField getTxtClienteDireccion() {
        return TxtClienteDireccion;
    }

    /**
     * @param TxtClienteDireccion the TxtClienteDireccion to set
     */
    public void setTxtClienteDireccion(javax.swing.JTextField TxtClienteDireccion) {
        this.TxtClienteDireccion = TxtClienteDireccion;
    }

    /**
     * @return the TxtClienteEmail
     */
    public javax.swing.JTextField getTxtClienteEmail() {
        return TxtClienteEmail;
    }

    /**
     * @param TxtClienteEmail the TxtClienteEmail to set
     */
    public void setTxtClienteEmail(javax.swing.JTextField TxtClienteEmail) {
        this.TxtClienteEmail = TxtClienteEmail;
    }

    /**
     * @return the TxtClienteNombre
     */
    public javax.swing.JTextField getTxtClienteNombre() {
        return TxtClienteNombre;
    }

    /**
     * @param TxtClienteNombre the TxtClienteNombre to set
     */
    public void setTxtClienteNombre(javax.swing.JTextField TxtClienteNombre) {
        this.TxtClienteNombre = TxtClienteNombre;
    }

    /**
     * @return the TxtClienteTelefono
     */
    public javax.swing.JTextField getTxtClienteTelefono() {
        return TxtClienteTelefono;
    }

    /**
     * @param TxtClienteTelefono the TxtClienteTelefono to set
     */
    public void setTxtClienteTelefono(javax.swing.JTextField TxtClienteTelefono) {
        this.TxtClienteTelefono = TxtClienteTelefono;
    }

    /**
     * @return the jButton4
     */
    public javax.swing.JButton getjButton4() {
        return jButton4;
    }

    /**
     * @param jButton4 the jButton4 to set
     */
    public void setjButton4(javax.swing.JButton jButton4) {
        this.jButton4 = jButton4;
    }
        
}
