/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotienda;

import conexionmysql.ConectarMySQL;
import conexionmysql.DatosConexion;
import static conexionmysql.DatosConexion.CONEXION;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kote
 */
public class Facturaa extends javax.swing.JFrame implements DatosConexion{

   
DefaultTableModel DfmodeloListaProductosFactura = new DefaultTableModel();
DefaultTableModel DfmodeloProductos = new DefaultTableModel();
DefaultTableModel DfmodeloClientes = new DefaultTableModel();

Map <String,Producto> productosFactura = new HashMap<>();
      
    /**
     * Creates new form Facturaa
     */
    public Facturaa() {
        initComponents();
        txtFechaFactura.setEnabled(false);
        txtFechaFactura.setText(getFecha());
          //vaciamos la tabla de filas
       DfmodeloClientes.setColumnCount(0);
       DfmodeloClientes.setRowCount(0);
       //Añadimos las columnas al modelo de la tabla para los clientes
       DfmodeloClientes.addColumn("COD");
       DfmodeloClientes.addColumn("NOMBRE");
       DfmodeloClientes.addColumn("APELLIDOS");
       DfmodeloClientes.addColumn("DNI");
       DfmodeloClientes.addColumn("DIRECCION");
       DfmodeloClientes.addColumn("E-mail");
       DfmodeloClientes.addColumn("TELEFONO");
       DfmodeloClientes.addColumn("SEXO");
       //vaciamos la tabla de columnas y filas
        DfmodeloProductos.setColumnCount(0);
        DfmodeloProductos.setRowCount(0);
        //Creamos las columnas de las tablas y laas añadimos al defautTable
        DfmodeloProductos.addColumn("COD");
        DfmodeloProductos.addColumn("NOMBRE");
        DfmodeloProductos.addColumn("DETALLE");
        DfmodeloProductos.addColumn("PROVEEDOR");
        DfmodeloProductos.addColumn("PRECIO");
        DfmodeloProductos.addColumn("STOCK");
         //vaciamos la tabla de columnas y filas
        DfmodeloListaProductosFactura.setColumnCount(0);
        DfmodeloListaProductosFactura.setRowCount(0);
        DfmodeloListaProductosFactura.addColumn("Codigo");
        DfmodeloListaProductosFactura.addColumn("Descripcion");
        DfmodeloListaProductosFactura.addColumn("Cantidad");
        DfmodeloListaProductosFactura.addColumn("Precio x 1");
        DfmodeloListaProductosFactura.addColumn("Precio Venta");
        //Creamos la tabla
        JTable DatosFactura = new JTable(DfmodeloListaProductosFactura);
       //Añadimos el modelo de la tabla a la tabla
        TablaDatosFactura.add(DatosFactura);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaBuscarCliente = new javax.swing.JDialog();
        PanelBuscarClie = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DatoDNIBusquedaCliente = new javax.swing.JTextField();
        BtnBuscarClientesFactura = new javax.swing.JButton();
        BtnRegistrarClienteFac = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaBusquedaClientes = new javax.swing.JTable();
        BtnVolverClientesFactura = new javax.swing.JButton();
        VentanaBuscarArticulo = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DatoCodBusquedaArticulo = new javax.swing.JTextField();
        BtnBuscarArticuloFactura = new javax.swing.JButton();
        BtnVolverArticuloFactura = new javax.swing.JButton();
        BtnRegistrarProductoFac = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaBusquedaArticulo = new javax.swing.JTable();
        MenuEmOpcionesBusCli = new javax.swing.JPopupMenu();
        MenuEmModificarCli = new javax.swing.JMenuItem();
        MenuEmExportarCli = new javax.swing.JMenuItem();
        MenuEmOpcionesBusArti = new javax.swing.JPopupMenu();
        MenuEmExportarArt = new javax.swing.JMenuItem();
        PanelFondo = new javax.swing.JPanel();
        PanelCodFactura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        EtiIconoFactura = new javax.swing.JLabel();
        PanelDatosFactura = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtFacturaNombre = new javax.swing.JTextField();
        TxtFacturaDNI = new javax.swing.JTextField();
        TxtFacturaDireccion = new javax.swing.JTextField();
        BotonBuscarClieFac = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtFacturaCodigoCliente = new javax.swing.JTextField();
        txtFechaFactura = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BotonBuscarArtFac = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatosFactura = new javax.swing.JTable();
        PanelDatosFinalesFactura = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DatoSubTotalFac = new javax.swing.JTextField();
        DatoIVAFac = new javax.swing.JTextField();
        DatoDescuFac = new javax.swing.JTextField();
        DatoTotalFac = new javax.swing.JTextField();
        BotonCalcularOperacionFac = new javax.swing.JButton();
        BotonEliminarArticuloFac = new javax.swing.JButton();
        BotonRealizarVentaFac = new javax.swing.JButton();
        BotonSalirFac = new javax.swing.JButton();

        VentanaBuscarCliente.setMinimumSize(new java.awt.Dimension(688, 426));

        PanelBuscarClie.setMinimumSize(new java.awt.Dimension(668, 404));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Busquéda de cliente:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("DNI:");

        BtnBuscarClientesFactura.setText("Buscar");
        BtnBuscarClientesFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarClientesFacturaActionPerformed(evt);
            }
        });

        BtnRegistrarClienteFac.setText("Registrar Cliente");
        BtnRegistrarClienteFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarClienteFacActionPerformed(evt);
            }
        });

        TablaBusquedaClientes.setModel(DfmodeloClientes);
        TablaBusquedaClientes.setComponentPopupMenu(MenuEmOpcionesBusCli);
        jScrollPane2.setViewportView(TablaBusquedaClientes);

        BtnVolverClientesFactura.setText("Volver");
        BtnVolverClientesFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverClientesFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBuscarClieLayout = new javax.swing.GroupLayout(PanelBuscarClie);
        PanelBuscarClie.setLayout(PanelBuscarClieLayout);
        PanelBuscarClieLayout.setHorizontalGroup(
            PanelBuscarClieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarClieLayout.createSequentialGroup()
                .addGroup(PanelBuscarClieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBuscarClieLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel13))
                    .addGroup(PanelBuscarClieLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DatoDNIBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBuscarClientesFactura)
                        .addGap(32, 32, 32)
                        .addComponent(BtnVolverClientesFactura)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(BtnRegistrarClienteFac)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(PanelBuscarClieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        PanelBuscarClieLayout.setVerticalGroup(
            PanelBuscarClieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarClieLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addGap(25, 25, 25)
                .addGroup(PanelBuscarClieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(DatoDNIBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarClientesFactura)
                    .addComponent(BtnRegistrarClienteFac)
                    .addComponent(BtnVolverClientesFactura))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VentanaBuscarClienteLayout = new javax.swing.GroupLayout(VentanaBuscarCliente.getContentPane());
        VentanaBuscarCliente.getContentPane().setLayout(VentanaBuscarClienteLayout);
        VentanaBuscarClienteLayout.setHorizontalGroup(
            VentanaBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBuscarClie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        VentanaBuscarClienteLayout.setVerticalGroup(
            VentanaBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBuscarClie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        VentanaBuscarArticulo.setMinimumSize(new java.awt.Dimension(658, 377));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Busquéda de artículo:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Cod:");

        BtnBuscarArticuloFactura.setText("Buscar");
        BtnBuscarArticuloFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarArticuloFacturaActionPerformed(evt);
            }
        });

        BtnVolverArticuloFactura.setText("Volver");
        BtnVolverArticuloFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverArticuloFacturaActionPerformed(evt);
            }
        });

        BtnRegistrarProductoFac.setText("Registrar Producto");
        BtnRegistrarProductoFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarProductoFacActionPerformed(evt);
            }
        });

        TablaBusquedaArticulo.setModel(DfmodeloProductos);
        TablaBusquedaArticulo.setComponentPopupMenu(MenuEmOpcionesBusArti);
        jScrollPane3.setViewportView(TablaBusquedaArticulo);

        javax.swing.GroupLayout VentanaBuscarArticuloLayout = new javax.swing.GroupLayout(VentanaBuscarArticulo.getContentPane());
        VentanaBuscarArticulo.getContentPane().setLayout(VentanaBuscarArticuloLayout);
        VentanaBuscarArticuloLayout.setHorizontalGroup(
            VentanaBuscarArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaBuscarArticuloLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatoCodBusquedaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnBuscarArticuloFactura)
                .addGap(32, 32, 32)
                .addComponent(BtnVolverArticuloFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(BtnRegistrarProductoFac)
                .addGap(45, 45, 45))
            .addGroup(VentanaBuscarArticuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaBuscarArticuloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(231, 231, 231))
        );
        VentanaBuscarArticuloLayout.setVerticalGroup(
            VentanaBuscarArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaBuscarArticuloLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addGroup(VentanaBuscarArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(DatoCodBusquedaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarArticuloFactura)
                    .addComponent(BtnRegistrarProductoFac)
                    .addComponent(BtnVolverArticuloFactura))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        MenuEmModificarCli.setText("Modificar");
        MenuEmOpcionesBusCli.add(MenuEmModificarCli);

        MenuEmExportarCli.setText("Exportar Datos");
        MenuEmExportarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmExportarCliActionPerformed(evt);
            }
        });
        MenuEmOpcionesBusCli.add(MenuEmExportarCli);

        MenuEmExportarArt.setText("Exportar Producto");
        MenuEmExportarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmExportarArtActionPerformed(evt);
            }
        });
        MenuEmOpcionesBusArti.add(MenuEmExportarArt);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Factura nº:");

        EtiIconoFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpg/icon_factura.png"))); // NOI18N

        javax.swing.GroupLayout PanelCodFacturaLayout = new javax.swing.GroupLayout(PanelCodFactura);
        PanelCodFactura.setLayout(PanelCodFacturaLayout);
        PanelCodFacturaLayout.setHorizontalGroup(
            PanelCodFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCodFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCodFacturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EtiIconoFactura)
                .addGap(56, 56, 56))
        );
        PanelCodFacturaLayout.setVerticalGroup(
            PanelCodFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCodFacturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCodFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EtiIconoFactura))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Señor/a:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("DNI:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Dirección:");

        BotonBuscarClieFac.setText("Buscar");
        BotonBuscarClieFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarClieFacActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Código:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Fecha:");

        txtFechaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFacturaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Artículo:");

        BotonBuscarArtFac.setText("Buscar");
        BotonBuscarArtFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarArtFacActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TU TIENDA");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelDatosFacturaLayout = new javax.swing.GroupLayout(PanelDatosFactura);
        PanelDatosFactura.setLayout(PanelDatosFacturaLayout);
        PanelDatosFacturaLayout.setHorizontalGroup(
            PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosFacturaLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(PanelDatosFacturaLayout.createSequentialGroup()
                        .addGroup(PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosFacturaLayout.createSequentialGroup()
                                .addGroup(PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelDatosFacturaLayout.createSequentialGroup()
                                        .addGap(290, 290, 290)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFechaFactura)
                                            .addComponent(BotonBuscarArtFac, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                                    .addGroup(PanelDatosFacturaLayout.createSequentialGroup()
                                        .addGroup(PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(PanelDatosFacturaLayout.createSequentialGroup()
                                                .addComponent(TxtFacturaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9))
                                            .addComponent(TxtFacturaNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelDatosFacturaLayout.createSequentialGroup()
                                                .addComponent(TxtFacturaCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel10)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(BotonBuscarClieFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(PanelDatosFacturaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtFacturaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        PanelDatosFacturaLayout.setVerticalGroup(
            PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtFacturaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarClieFac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtFacturaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(TxtFacturaCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(PanelDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtFacturaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(BotonBuscarArtFac))
                .addContainerGap())
        );

        TablaDatosFactura.setModel(DfmodeloListaProductosFactura
        );
        jScrollPane1.setViewportView(TablaDatosFactura);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Subtotal:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("IVA:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Descuento:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Total:");

        javax.swing.GroupLayout PanelDatosFinalesFacturaLayout = new javax.swing.GroupLayout(PanelDatosFinalesFactura);
        PanelDatosFinalesFactura.setLayout(PanelDatosFinalesFacturaLayout);
        PanelDatosFinalesFacturaLayout.setHorizontalGroup(
            PanelDatosFinalesFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosFinalesFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatoSubTotalFac, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DatoIVAFac, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatoDescuFac, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatoTotalFac, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDatosFinalesFacturaLayout.setVerticalGroup(
            PanelDatosFinalesFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosFinalesFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosFinalesFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(DatoSubTotalFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatoIVAFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatoDescuFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatoTotalFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotonCalcularOperacionFac.setText("Calcular Operación");

        BotonEliminarArticuloFac.setText("Eliminar Articulo");

        BotonRealizarVentaFac.setText("Realizar Venta");

        BotonSalirFac.setText("Salir");
        BotonSalirFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirFacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelFondoLayout.createSequentialGroup()
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(PanelDatosFinalesFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonSalirFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonRealizarVentaFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonEliminarArticuloFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonCalcularOperacionFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelFondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PanelDatosFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelCodFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDatosFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelCodFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelDatosFinalesFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BotonCalcularOperacionFac)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEliminarArticuloFac)
                        .addGap(19, 19, 19)
                        .addComponent(BotonRealizarVentaFac)
                        .addGap(18, 18, 18)
                        .addComponent(BotonSalirFac)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirFacActionPerformed
        setVisible(false);
    }//GEN-LAST:event_BotonSalirFacActionPerformed

    private void BotonBuscarClieFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarClieFacActionPerformed
        VentanaBuscarCliente.setVisible(true);
        resultadoListaClientes();
    }//GEN-LAST:event_BotonBuscarClieFacActionPerformed

    private void BtnBuscarClientesFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarClientesFacturaActionPerformed

    }//GEN-LAST:event_BtnBuscarClientesFacturaActionPerformed

    private void BtnRegistrarClienteFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarClienteFacActionPerformed
       Cliente nuevoClienteFactura = new Cliente();
       this.dispose();
    }//GEN-LAST:event_BtnRegistrarClienteFacActionPerformed

    private void BtnVolverClientesFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverClientesFacturaActionPerformed
        VentanaBuscarCliente.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_BtnVolverClientesFacturaActionPerformed

    private void BtnBuscarArticuloFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarArticuloFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarArticuloFacturaActionPerformed

    private void BtnVolverArticuloFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverArticuloFacturaActionPerformed
        VentanaBuscarArticulo.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_BtnVolverArticuloFacturaActionPerformed

    private void BtnRegistrarProductoFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarProductoFacActionPerformed
       Producto nuevoProductoFactura = new Producto();
       this.dispose();
    }//GEN-LAST:event_BtnRegistrarProductoFacActionPerformed

    private void MenuEmExportarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmExportarCliActionPerformed
        exportarDatosClientes();
    }//GEN-LAST:event_MenuEmExportarCliActionPerformed

    private void MenuEmExportarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmExportarArtActionPerformed
        añadirProductoFactura();
    }//GEN-LAST:event_MenuEmExportarArtActionPerformed

    private void BotonBuscarArtFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarArtFacActionPerformed
        VentanaBuscarArticulo.setVisible(true);
        resultadoListaProductos();
    }//GEN-LAST:event_BotonBuscarArtFacActionPerformed

    private void txtFechaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFacturaActionPerformed
       
    }//GEN-LAST:event_txtFechaFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturaa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarArtFac;
    private javax.swing.JButton BotonBuscarClieFac;
    private javax.swing.JButton BotonCalcularOperacionFac;
    private javax.swing.JButton BotonEliminarArticuloFac;
    private javax.swing.JButton BotonRealizarVentaFac;
    private javax.swing.JButton BotonSalirFac;
    private javax.swing.JButton BtnBuscarArticuloFactura;
    private javax.swing.JButton BtnBuscarClientesFactura;
    private javax.swing.JButton BtnRegistrarClienteFac;
    private javax.swing.JButton BtnRegistrarProductoFac;
    private javax.swing.JButton BtnVolverArticuloFactura;
    private javax.swing.JButton BtnVolverClientesFactura;
    private javax.swing.JTextField DatoCodBusquedaArticulo;
    private javax.swing.JTextField DatoDNIBusquedaCliente;
    private javax.swing.JTextField DatoDescuFac;
    private javax.swing.JTextField DatoIVAFac;
    private javax.swing.JTextField DatoSubTotalFac;
    private javax.swing.JTextField DatoTotalFac;
    private javax.swing.JLabel EtiIconoFactura;
    private javax.swing.JMenuItem MenuEmExportarArt;
    private javax.swing.JMenuItem MenuEmExportarCli;
    private javax.swing.JMenuItem MenuEmModificarCli;
    private javax.swing.JPopupMenu MenuEmOpcionesBusArti;
    private javax.swing.JPopupMenu MenuEmOpcionesBusCli;
    private javax.swing.JPanel PanelBuscarClie;
    private javax.swing.JPanel PanelCodFactura;
    private javax.swing.JPanel PanelDatosFactura;
    private javax.swing.JPanel PanelDatosFinalesFactura;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JTable TablaBusquedaArticulo;
    private javax.swing.JTable TablaBusquedaClientes;
    private javax.swing.JTable TablaDatosFactura;
    private javax.swing.JTextField TxtFacturaCodigoCliente;
    private javax.swing.JTextField TxtFacturaDNI;
    private javax.swing.JTextField TxtFacturaDireccion;
    private javax.swing.JTextField TxtFacturaNombre;
    private javax.swing.JDialog VentanaBuscarArticulo;
    private javax.swing.JDialog VentanaBuscarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtFechaFactura;
    // End of variables declaration//GEN-END:variables

    private void exportarDatosClientes() {
        int row=TablaBusquedaClientes.getSelectedRow();
        String cod = TablaBusquedaClientes.getValueAt(row, 0).toString();
        String nombre = TablaBusquedaClientes.getValueAt(row, 1).toString();
        String apellidos = TablaBusquedaClientes.getValueAt(row, 2).toString();
        String dni = TablaBusquedaClientes.getValueAt(row, 3).toString();
        String direccion = TablaBusquedaClientes.getValueAt(row, 4).toString();
        
        TxtFacturaCodigoCliente.setText(cod);
        TxtFacturaNombre.setText(nombre+" "+apellidos);
        TxtFacturaDireccion.setText(direccion);
        TxtFacturaDNI.setText(dni);
        
        VentanaBuscarCliente.setVisible(false);
    }
public String getFecha(){
     Date fecha1 = new Date();
     SimpleDateFormat formatoFecha =new SimpleDateFormat("dd-MM-yyyy");
     return formatoFecha.format(fecha1);
    }

public void añadirProductoFactura(){
        int row=TablaBusquedaArticulo.getSelectedRow();
        String cod = TablaBusquedaArticulo.getValueAt(row, 0).toString();
        String nombre = TablaBusquedaArticulo.getValueAt(row, 1).toString();
        String proovedor = TablaBusquedaArticulo.getValueAt(row, 3).toString();
        String precio = TablaBusquedaArticulo.getValueAt(row, 4).toString();
        
       
        
        Producto productoFactura =new Producto(cod,nombre, proovedor, Float.parseFloat(precio));
        
        productosFactura.put(cod, productoFactura);
        DfmodeloListaProductosFactura.setRowCount(0);
        for (Map.Entry<String,Producto> e : productosFactura.entrySet()){
            DfmodeloListaProductosFactura.addRow(new Object[] {e.getValue().getCodigo(),e.getValue().getNombre(),
                e.getValue().getProveedor(),e.getValue().getPrecioVenta()});
       //Creamos la tabla 
       JTable DatosProductosFac = new JTable(DfmodeloListaProductosFactura);
       //Añadimos el modelo de la tabla a la tabla
       TablaDatosFactura.add(DatosProductosFac);
       TablaDatosFactura.setVisible(true);
    }
    }

private void resultadoListaClientes() {
        try {
           DfmodeloClientes.setRowCount(0);
           ResultSet filas = CONEXION.Consultar("select * from clientes order by codigoCli;");
                     while(filas.next()){
                       DfmodeloClientes.addRow(new Object[] {filas.getString(1),filas.getString(2),filas.getString(3),filas.getString(4),
                       filas.getString(5),filas.getString(6),filas.getInt(7),filas.getString(8)});
                       //Creamos la tabla 
                       JTable DatosCliente = new JTable(DfmodeloClientes);
                       //Añadimos el modelo de la tabla a la tabla
                       TablaBusquedaClientes.add(DatosCliente);
                       }
               TablaBusquedaClientes.setVisible(true);
       } catch (SQLException ex) {
           Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
       }
    }

private void resultadoListaProductos() {
        try {
             DfmodeloProductos.setRowCount(0);
             ResultSet filas = CONEXION.Consultar("select * from productos order by codigoPro;");
                while(filas.next()){

                   DfmodeloProductos.addRow(new Object[] {filas.getString(1),filas.getString(2),filas.getString(3),filas.getString(4),
                   filas.getDouble(5),filas.getInt(6)});
                   //Creamos la tabla 
                   JTable DatosProducto = new JTable(DfmodeloProductos);
                   //Añadimos el modelo de la tabla a la tabla
                   TablaBusquedaArticulo.add(DatosProducto);
                   }
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
