/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotienda;

import conexionmysql.ConectarMySQL;
import conexionmysql.DatosConexion;
import java.awt.GraphicsConfiguration;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kote
 */
public class Producto extends javax.swing.JFrame implements DatosConexion{
    
    private String codigo ;
    private String nombre ;
    private String detalle;
    private String Proveedor ;
    private double precioCompra ;
    private double precioVenta ;
    private int stock ;

    public Producto(GraphicsConfiguration gc) {
        super(gc);
    }
    

    public Producto(String codigo, String nombre,  String Proveedor, double precioVenta) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.Proveedor = Proveedor;
        this.precioVenta = precioVenta;
    }
    
DefaultTableModel DfmodeloProductos = new DefaultTableModel();
 
    /**
     * Creates new form Producto
     */
    public Producto() {
        initComponents();
        
        //vaciamos la tabla de columnas y filas
        DfmodeloProductos.setColumnCount(0);
        DfmodeloProductos.setRowCount(0);
        //Creamos las columnas de las tablas y laas añadimos al defautTable
        DfmodeloProductos.addColumn("COD");
        DfmodeloProductos.addColumn("NOMBRE");
        DfmodeloProductos.addColumn("DETALLE");
        DfmodeloProductos.addColumn("PROVEEDOR");
        DfmodeloProductos.addColumn("PRECIO");
        DfmodeloProductos.addColumn("STOCK");
        
        resultadoListaProductos();
        TxtProductoCodigo.setText(calcula_IDProducto());
        TxtProductoCodigo.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatosProducto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtProductoCodigo = new javax.swing.JTextField();
        TxtProductoNombre = new javax.swing.JTextField();
        TxtProductoStock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtProductoPrecioCompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtProductoDetalle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtProductoProveedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtProductoPrecioVenta = new javax.swing.JTextField();
        PanelListaProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListaProductos = new javax.swing.JTable();
        PanelBotonesProducto = new javax.swing.JPanel();
        BtnAgregarProducto = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRODUCTO");

        PanelDatosProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CODIGO:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("STOCK:");

        TxtProductoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoCodigoActionPerformed(evt);
            }
        });

        TxtProductoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoNombreActionPerformed(evt);
            }
        });

        TxtProductoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoStockActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("PRECIO COMPRA:");

        TxtProductoPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoPrecioCompraActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("DETALLE:");

        TxtProductoDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoDetalleActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PROVEEDOR:");

        TxtProductoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoProveedorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("PRECIO VENTA:");

        TxtProductoPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoPrecioVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosProductoLayout = new javax.swing.GroupLayout(PanelDatosProducto);
        PanelDatosProducto.setLayout(PanelDatosProductoLayout);
        PanelDatosProductoLayout.setHorizontalGroup(
            PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosProductoLayout.createSequentialGroup()
                        .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelDatosProductoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtProductoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(TxtProductoStock)))
                    .addGroup(PanelDatosProductoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosProductoLayout.createSequentialGroup()
                        .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtProductoDetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addComponent(TxtProductoProveedor, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(PanelDatosProductoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtProductoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtProductoPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        PanelDatosProductoLayout.setVerticalGroup(
            PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TxtProductoPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TxtProductoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtProductoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(PanelDatosProductoLayout.createSequentialGroup()
                        .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(TxtProductoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(PanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtProductoStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelListaProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        TablaListaProductos.setModel(DfmodeloProductos);
        jScrollPane1.setViewportView(TablaListaProductos);

        javax.swing.GroupLayout PanelListaProductosLayout = new javax.swing.GroupLayout(PanelListaProductos);
        PanelListaProductos.setLayout(PanelListaProductosLayout);
        PanelListaProductosLayout.setHorizontalGroup(
            PanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        PanelListaProductosLayout.setVerticalGroup(
            PanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnAgregarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnAgregarProducto.setText("Agregar");
        BtnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarProductoActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesProductoLayout = new javax.swing.GroupLayout(PanelBotonesProducto);
        PanelBotonesProducto.setLayout(PanelBotonesProductoLayout);
        PanelBotonesProductoLayout.setHorizontalGroup(
            PanelBotonesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelBotonesProductoLayout.setVerticalGroup(
            PanelBotonesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBotonesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregarProducto)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDatosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelListaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBotonesProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDatosProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelListaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBotonesProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtProductoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoCodigoActionPerformed
        
    }//GEN-LAST:event_TxtProductoCodigoActionPerformed

    private void TxtProductoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProductoNombreActionPerformed

    private void TxtProductoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProductoStockActionPerformed

    private void TxtProductoPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProductoPrecioCompraActionPerformed

    private void TxtProductoDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProductoDetalleActionPerformed

    private void TxtProductoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProductoProveedorActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        this.dispose();
        
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BtnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarProductoActionPerformed
        agregarProducto();
        resultadoListaProductos();
    }//GEN-LAST:event_BtnAgregarProductoActionPerformed

    private void TxtProductoPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProductoPrecioVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Producto().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarProducto;
    private javax.swing.JPanel PanelBotonesProducto;
    private javax.swing.JPanel PanelDatosProducto;
    private javax.swing.JPanel PanelListaProductos;
    private javax.swing.JTable TablaListaProductos;
    private javax.swing.JTextField TxtProductoCodigo;
    private javax.swing.JTextField TxtProductoDetalle;
    private javax.swing.JTextField TxtProductoNombre;
    private javax.swing.JTextField TxtProductoPrecioCompra;
    private javax.swing.JTextField TxtProductoPrecioVenta;
    private javax.swing.JTextField TxtProductoProveedor;
    private javax.swing.JTextField TxtProductoStock;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void agregarProducto() throws NumberFormatException {
        
         codigo = this.TxtProductoCodigo.getText();
         nombre = TxtProductoNombre.getText();
         detalle = TxtProductoDetalle.getText();
         Proveedor = TxtProductoProveedor.getText();
         precioCompra = Double.parseDouble(TxtProductoPrecioCompra.getText());
         precioVenta = Double.parseDouble(TxtProductoPrecioVenta.getText());
         stock = Integer.parseInt(TxtProductoStock.getText());
        
        CONEXION.ejecutar("insert into productos values('"+codigo+"','"+nombre+"','"+detalle+"','"+Proveedor+"'"
                 + ",'"+precioCompra+"','"+stock+"');");
    
        
        TxtProductoDetalle.setText("");
        TxtProductoPrecioCompra.setText("");
        TxtProductoNombre.setText("");
        TxtProductoProveedor.setText("");
        TxtProductoStock.setText("");
        TxtProductoCodigo.setText(calcula_IDProducto());
        resultadoListaProductos();
    }

    private void resultadoListaProductos() {
        try {
             DfmodeloProductos.setRowCount(0);
             ResultSet filas = CONEXION.Consultar("select * from productos order by codigoPro;");
                while(filas.next()){

                   DfmodeloProductos.addRow(new Object[] {filas.getString(1),filas.getString(2),filas.getString(3),filas.getString(4),
                   filas.getDouble(5),filas.getInt(6)});
                   //Creamos la tabla 
                   JTable DatosProducto = new JTable(DfmodeloProductos);
                   //Añadimos el modelo de la tabla a la tabla
                   TablaListaProductos.add(DatosProducto);
                   }
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private String calcula_IDProducto(){
        ResultSet datos = CONEXION.Consultar("select count(*) num_Productos from productos");
        String id_Retornado="";
        try {
            while(datos.next()){
                if(datos.getInt("num_Productos")==0){
                    id_Retornado =  "P1";
                }else{
                    ResultSet ultimo_ID = CONEXION.Consultar("select codigoPro from productos order by codigoPro desc limit 1;");
                    while(ultimo_ID.next()){
                        id_Retornado = ultimo_ID.getString("codigoPro");
                    }
                    id_Retornado = id_Retornado.substring(1, id_Retornado.length());
                    int numero = Integer.valueOf(id_Retornado)+1;
                    id_Retornado = "P"+numero;   
                }
            }  // P-13
        } catch (SQLException ex) {}

        return id_Retornado;
    }

    /**
     * @return the codigo
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the detalle
     */
    public String getDetalle() {
        return detalle;
    }

    /**
     * @param detalle the detalle to set
     */
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    /**
     * @return the Proveedor
     */
    public String getProveedor() {
        return Proveedor;
    }

    /**
     * @param Proveedor the Proveedor to set
     */
    public void setProveedor(String Proveedor) {
        this.Proveedor = Proveedor;
    }

    /**
     * @return the precioCompra
     */
    public double getPrecioCompra() {
        return precioCompra;
    }

    /**
     * @param precioCompra the precioCompra to set
     */
    public void setPrecioCompra(float precioCompra) {
        this.precioCompra = precioCompra;
    }

    /**
     * @return the precioVenta
     */
    public double getPrecioVenta() {
        return precioVenta;
    }

    /**
     * @param precioVenta the precioVenta to set
     */
    public void setPrecioVenta(float precioVenta) {
        this.precioVenta = precioVenta;
    }

    /**
     * @return the stock
     */
    public int getStock() {
        return stock;
    }

    /**
     * @param stock the stock to set
     */
    public void setStock(int stock) {
        this.stock = stock;
    }
    
    

}
